### PR TITLE
stepper/temperature ISR tasking. Remove need for checkRX.

### PR DESCRIPTION
**Pull request by thess**
FWIW - Here's a set of changes to the way the temperature and stepper ISRs behave. The idea here is to run these ISRs as if they were high-priority tasks which can preempt other processing. We also keep interrupts enabled for critical events such as serial receiving, run-outs, etc. The stepper ISR has the highest priority and will hold off the temperature task until the stepper task completes. There is no need to ever call checkRx when things are structured correctly.

Similar code changes have been running on my 2 MK2S machines for well over a year (I don't think I missed anything porting it forwared). I can use the serial interface at 250000 with an RPi-3 B+ hooked up. I don't know if the RPi-0 attached to my MK3S can handle that baud-rate - I haven't tried it yet.

I am submitting these changes here for consideration if it solves your issue with checkRx.

### CODE REVIEW

**Comment by thess** [comment]
Updated to latest wavexx:MK3_LA15 mods. Removed need for additional checkRx! I haven't tested these latest updates yet as I am currently upgrading my MK3S with MMU2S kit just received this week! it does compile.

BTW - I build a single lanaguage version without BOOTAPP and W25X20CL support. It leaves me about 20K of program space to hack in.

**Comment by wavexx** [comment]
I started to have a look at this. Do you know if prusa added checkRx _because_ of LA1.0, of if that was already existing?

I have the impression they sprinkled a few of these calls because the isr took to long, but some of the places where the call was done do not make much sense. This could have been the case in LA1.0 when too many esteps were scheduled, essentially running the isr full time during the beginning and end of an acceleration phase.

For instance, the isr now takes on average 50µs, with advance steps taking 10µ. I've driven the MK3 for a couple of prints with the serial at 115200 bps without the need of any call to checkRx or isr tasking, because there's always plenty of time to drain the buffer.

I currently still added those calls back, but in two places _only_ (20% and 60% of the main isr), and again mostly to be on the defensive for Prusa.

I actually never managed to connect via serial at 230400 bps on a mega on my system due to some issues in the hub I'm using, so I "guess" it "could" be possible (although -- for printing 230kbps is irrelevant).

**Comment by thess** [comment]
All things considered, it may have just been my preference to cleanup the serial port and line handling. I did not care for the polling of serial interfaces within an ISR or even from a critical task. If the serial input is that critical it needs to be an interrupt which should not be masked longer than 1 character time after RCV complete flag.

At 250000 baud, I saw receiver errors - this change eliminated them. Also, I don't think you can operate a 16MHz AVR at 230400 baud reliably due to clock speed/divisors. If your host can handle 250000, things work OK.

**Notes:**
* Removing the checkRx calls and routine saves precious code space.
* Cleaner task execution structure and less kludgery second guessing 3rd order effects. There is no need to execute the stepper and temperature processes inside an ISR.
* With DEBUG_STEPPER_TIMER_MISSED enabled, I have not seen a single alert.
* Due to the half-duplex nature of the G-code protocols, higher baud is generally better.

**Comment by wavexx** [comment]
As a further note, while checking this, there is some bad interaction that can happen with babystep insertion with this, as the heater management "indirectly" applies them. It might result in lost Z steps depending on where they are inserted. Unlikely, but a possibility.

I'm going through the babystep code in the DEDGE branch and noticed of this (and other) issue.
It's something to consider, and it would be nice to remove babystep management from there.

**Comment by thess** [comment]
Closing this - never had it working to my satisfaction and it now conflicts with current firmware base. I have no plans to work on this anymore.

**Comment by wavexx** [comment]
I still think we can remove checkRx completely, but I need to setup some testing sequence in order to ensure that this is true.

**Pull request closed without merging**
